TrezycraftConfig:
  type: world
  events:
    on reload scripts:
    ############################################################################
    # GENERAL CONFIGURATION
    ############################################################################

    # Add modules to this list to enable them
    - define enabledModules li@Loot

    ############################################################################
    # INITIALIZE
    ############################################################################

    # Clear any previously enabled modules
    - flag global enabledModules:!

    # Enable modules
    - foreach <%enabledModules%> {
      - if <proc[EnableModule].context[%value%]> {
        - narrate 'Enabled the <%value%> module.'
        } else {
        - narrate 'Failed to load the <%module%> module.'
        }
      }
    - narrate <global.flag[enabledModules]>